### PR TITLE
Added support for joystick identification

### PR DESCRIPTION
**Pull request by zsbzsb**
Tested with XBox 360 controller and was able to get all the information. Also note that this is the same as #96 with regards to having an internal struct for marshaling the data.

### CODE REVIEW

**Comment by LaurentGomila** [comment]
Same remarks as in #96.

**Comment by zsbzsb** [comment]
And done :)

**Comment by LaurentGomila** [comment]
VendorID -> VendorId
ProductID -> ProductId

In case you wonder, I checked and the names are ok in CSFML.

**Comment by zsbzsb** [comment]
Well in C# we are capitalizing stuff. camelCase -> CamelCase  but this was a kinda unique case. :P

Updated... :)

**Pull request merged**
